name: train-my-model
on: [push]
jobs:
  train:
    runs-on: [self-hosted,cml,gpu]
    container:
      image: docker://iterativeai/cml:0-dvc2-base1-gpu
      options: --gpus all
    steps:
      - uses: actions/checkout@v3
      - name: cml-runner
        run: |
          nvidia-smi >> report.md
          cml send-comment report.md
