name: train-my-model
on: [push]
jobs:
  train:
    runs-on: [self-hosted, cml, gpu]
    steps:
      - uses: actions/checkout@v2
      - name: cml-runner
        run: |
          nvidia-smi >> report1.md
          cml send-comment report1.md
